development:
  adapter: mysql
  encoding: unicode
  database: visitmee_development
  pool: 5
  username: root
  password: bandana
test:
  adapter: mysql
  encoding: unicode
  database: visitmee_test
  pool: 5
  username: root
  password: bandana
production:
  adapter: postgresql
  encoding: unicode
  database: myapp
  pool: 5
  username: bishisht
  password: bandana
