development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: bishisht
  password: bandana
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: bishisht
  password: bandana
production:
  adapter: postgresql
  encoding: unicode
  database: myapp
  pool: 5
  username: bishisht
  password: bandana